In [3]:
action_table = {
    'left' : 0,
    'down' : 1,
    'right' : 2,
    'up' : 3
}

inv_action_table = {v: k for k, v in action_table.items()}

def get_optimal_policy(Q):
    optimal = [ inv_action_table[v] for v in Q.argmax(1)]
    return np.reshape(optimal,(4, 4))

In [20]:
import gym
import numpy as np

env = gym.make('FrozenLake-v0')
#env.monitor.start('recordings', force=True)

# Initialize Q matrix to zeros
Q = np.zeros((env.observation_space.n, env.action_space.n)) + 0.25

# Probability of random action
epsilon = 0.5
epsilon_decay = 0.9999

# Learning rate
alpha = 0.05

num_episodes = 20000
#old_optimal = get_optimal_policy(Q)
for n in xrange(num_episodes):
    observation = env.reset()
    done = False

    while not done:
        # Current state
        state = observation

        if np.random.rand() > epsilon:
            # Choose best action according to current Q matrix
            action = np.argmax(Q[state, :])
        else:
            # Take a random action
            action = env.action_space.sample()

        # Take action and observe state and reward
        observation, reward, done, info = env.step(action)
        
        if (done is True and reward == 0):
            reward = -0.1

        reward -= 0.001 # cost of life
        # Q-learning update
        Q[state, action] += alpha * (reward + np.max(Q[observation, :]) - Q[state, action])

    # Decay epsilon
    epsilon *= epsilon_decay
    
    if n % int(num_episodes/3) == 0: 
        print '------------' + str(n)+ '----------------------'
        print epsilon
        #new_optimal = get_optimal_policy(Q)
        #if (old_optimal == new_optimal).all():
        #    print 'Optimal strategy not changed. Stopping.'
        #    print new_optimal
        #    #break
        #old_optimal = new_optimal

#env.monitor.close()
print get_optimal_policy(Q)

[2016-07-01 07:16:27,593] Making new env: FrozenLake-v0


[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]]
------------0----------------------
0.49995
------------6666----------------------
0.256691445184
------------13332----------------------
0.131794175479
------------19998----------------------
0.0676676415055
[['left' 'up' 'up' 'up']
 ['left' 'left' 'left' 'left']
 ['up' 'down' 'left' 'left']
 ['left' 'right' 'down' 'left']]


### Test Run

In [21]:
env.monitor.start('recordings', force=True)
num_episodes = 1000

for n in xrange(num_episodes):
    observation = env.reset()
    done = False

    while not done:
        # Current state
        state = observation

        action = np.argmax(Q[state, :])

        # Take action and observe state and reward
        observation, reward, done, info = env.step(action)
        
        #if (done is True and reward == 0):
        #    reward = -0.1

        #reward -= 0.001 # cost of life
        # Q-learning update
        # Q[state, action] += alpha * (reward + np.max(Q[observation, :]) - Q[state, action])

    # Decay epsilon
    epsilon *= epsilon_decay

env.monitor.close()



[2016-07-01 07:17:44,720] Clearing 22 monitor files from previous run (because force=True was provided)
[2016-07-01 07:17:44,725] Starting new video recorder writing to /notebooks/hjem/RL/recordings/openaigym.video.4.16978.video000000.json
[2016-07-01 07:17:44,729] Starting new video recorder writing to /notebooks/hjem/RL/recordings/openaigym.video.4.16978.video000001.json
[2016-07-01 07:17:44,734] Ending episode 4 because it reached the timestep limit of 100.
[2016-07-01 07:17:44,739] Starting new video recorder writing to /notebooks/hjem/RL/recordings/openaigym.video.4.16978.video000008.json
[2016-07-01 07:17:44,745] Ending episode 9 because it reached the timestep limit of 100.
[2016-07-01 07:17:44,755] Ending episode 13 because it reached the timestep limit of 100.
[2016-07-01 07:17:44,757] Ending episode 14 because it reached the timestep limit of 100.
[2016-07-01 07:17:44,777] Ending episode 26 because it reached the timestep limit of 100.
[2016-07-01 07:17:44,780] Starting new v

In [22]:
gym.upload('/notebooks/hjem/RL/recordings', api_key='sk_znZbtlUTlu1nJNqFLRIyA')

[2016-07-01 07:17:54,720] [FrozenLake-v0] Uploading 1000 episodes of training data
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecurepla

<Evaluation evaluation id=eval_mtFFYKaQWyGhr81nZRbNA at 0x7fb497b78618> JSON: {
  "created": 1467357476, 
  "env": "FrozenLake-v0", 
  "id": "eval_mtFFYKaQWyGhr81nZRbNA", 
  "object": "evaluation"
}